/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Dtos.AnalisisDTO;
import Dtos.AnalisisTablaDTO;
import Dtos.ClienteDTO;
import Dtos.ClienteTablaDTO;
import Dtos.ParametroDTO;
import Dtos.ParametroTablaDTO;
import Dtos.PruebaDTO;
import Dtos.PruebaTablaDTO;
import Dtos.ResultadoDTO;
import Negocio.IAnalisisNegocio;
import Negocio.ICategoriaNegocio;
import Negocio.IClienteNegocio;
import Negocio.IMedicionNegocio;
import Negocio.IParametroNegocio;
import Negocio.IPruebaNegocio;
import Negocio.IRegistroNegocio;
import Negocio.IReporteNegocio;
import Negocio.IResultadoNegocio;
import Utilidades.ButtonEditor;
import Utilidades.ButtonRenderer;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ang3lfco
 */
public class frmAdmResultados extends javax.swing.JFrame {
    private IClienteNegocio clienteNegocio;
    private IPruebaNegocio pruebaNegocio;
    private ICategoriaNegocio categoriaNegocio;
    private IAnalisisNegocio analisisNegocio;
    private IParametroNegocio parametroNegocio;
    private IMedicionNegocio medicionNegocio;
    private IRegistroNegocio registroNegocio;
    private IReporteNegocio reporteNegocio;
    private IResultadoNegocio resultadoNegocio;
    
    /**
     * Creates new form frmAdmPruebas
     */
    public frmAdmResultados(IClienteNegocio clienteNegocio, IAnalisisNegocio analisisNegocio, IPruebaNegocio pruebaNegocio, IParametroNegocio parametroNegocio, IResultadoNegocio resultadoNegocio) {
        initComponents();
        this.clienteNegocio = clienteNegocio;
        this.analisisNegocio = analisisNegocio;
        this.pruebaNegocio = pruebaNegocio;
        this.parametroNegocio = parametroNegocio;
        this.resultadoNegocio = resultadoNegocio;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        cargarDatos();
    }
    
    private void cargarDatos() {
        try {
            List<ClienteTablaDTO> clientes = clienteNegocio.buscarClientes();
            List<AnalisisTablaDTO> analisis = analisisNegocio.buscarAnalisis();
            List<PruebaTablaDTO> pruebas = pruebaNegocio.buscarPruebas();
            List<ParametroTablaDTO> parametros = parametroNegocio.buscarParametros();
            List<ResultadoDTO> resultados = resultadoNegocio.buscarResultados();

            
            DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
            model.setRowCount(0); 

            for (ResultadoDTO resultado : resultados) {
                ClienteDTO c = analisisNegocio.obtenerClientePorAnalisis(resultado.getIdAnalisis());
                String nombreC = c.getNombres() + " " + c.getApeliidoPaterno() + " " + c.getApellidoMaterno();
                // Agregar la fila a la tabla
                model.addRow(new Object[]{
                    nombreC,
                    resultado.getIdAnalisis(),
                    "prueba",
                    resultado.getIdParametro(),
                    resultado.getValor()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
//    private void configurarTabla() {
//        jTable1.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());
//
//        ButtonEditor editor = new ButtonEditor(
//            e -> JOptionPane.showMessageDialog(null, "Editar Prueba en fila: " + jTable1.getSelectedRow()), 
//            e -> JOptionPane.showMessageDialog(null, "Eliminar Prueba en fila: " + jTable1.getSelectedRow())
//        );
//
//        jTable1.getColumnModel().getColumn(3).setCellEditor(editor);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnAgregarResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 19, 71));
        jLabel1.setText("Administracion de Resultados.");

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Analisis", "Parametro", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        btnAgregarResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/more.png"))); // NOI18N
        btnAgregarResultado.setText("Agregar resultado");
        btnAgregarResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarResultadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarResultado)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarResultado)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarResultadoMouseClicked
        // TODO add your handling code here:
        frmRegistrarResultados result = new frmRegistrarResultados(resultadoNegocio);
        result.setVisible(true);
    }//GEN-LAST:event_btnAgregarResultadoMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmAdmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmAdmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmAdmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmAdmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmAdmResultados().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregarCategoria;
    private javax.swing.JLabel btnAgregarResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables
}
