/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Dtos.PruebaDTO;
import Dtos.PruebaTablaDTO;
import Negocio.ICategoriaNegocio;
import Negocio.IPruebaNegocio;
import Negocio.NegocioException;
import Utilidades.ButtonEditor;
import Utilidades.ButtonRenderer;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ang3lfco
 */
public class frmAdmPruebas extends javax.swing.JFrame {

    private IPruebaNegocio pruebaNegocio;
    private ICategoriaNegocio categoriaNegocio;
    /**
     * Creates new form frmAdmPruebas
     */
    public frmAdmPruebas(IPruebaNegocio pruebaNegocio, ICategoriaNegocio categoriaNegocio) throws NegocioException {
        initComponents();
        this.pruebaNegocio = pruebaNegocio;
        this.categoriaNegocio = categoriaNegocio;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        cargarDatos();
        configurarTabla();
    }
    
    private void cargarDatos() throws NegocioException {
        List<PruebaTablaDTO> pruebas = pruebaNegocio.buscarPruebas();
        
        DefaultTableModel model = (DefaultTableModel) tblPruebas.getModel();
        model.setRowCount(0);
        
        
        for (PruebaTablaDTO p: pruebas) {
            List<String> nombresDeParametros = pruebaNegocio.obtenerParametrosPorPrueba(p.getId());
            String parametroStr = String.join(", ", nombresDeParametros);
            String nombreCategoria = categoriaNegocio.buscarId(p.getIdCategoria()).getNombre();
            Object[] row = new Object[4];
            row[0] = p.getNombre();
            row[1] = parametroStr;
            row[2] = nombreCategoria;
            
            model.addRow(row);
        }
        tblPruebas.setRowHeight(40);
    }
    
    private void configurarTabla() {
        tblPruebas.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());

        ButtonEditor editor = new ButtonEditor(
            e -> {try {
                
                PruebaTablaDTO pruebaAEditar = pruebaNegocio.buscarPruebas().get(tblPruebas.getSelectedRow());
                int id = pruebaAEditar.getId(); 
                String nombre = pruebaAEditar.getNombre();
                int idCategoria = pruebaAEditar.getIdCategoria();
                boolean estaBorrado = pruebaAEditar.isEstaBorrado();
                PruebaDTO prueba = new PruebaDTO(id, nombre, idCategoria, estaBorrado);
                
                frmEditarPrueba frmPrueba = new frmEditarPrueba(pruebaNegocio, prueba);
                frmPrueba.setVisible(true);
            } catch (NegocioException ex) {
                Logger.getLogger(frmAdmPruebas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                    }, 
            e -> {
            try {
                PruebaTablaDTO pruebaBorrar = pruebaNegocio.buscarPruebas().get(tblPruebas.getSelectedRow());
                pruebaNegocio.eliminar(pruebaBorrar.getId());
                JOptionPane.showMessageDialog(null, "Eliminó Prueba en fila: " + tblPruebas.getSelectedRow());
            } catch (NegocioException ex) {
                Logger.getLogger(frmAdmPruebas.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        );

        tblPruebas.getColumnModel().getColumn(3).setCellEditor(editor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPruebas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 19, 71));
        jLabel1.setText("Administracion de Pruebas.");

        tblPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Parametros", "Categoria", ""
            }
        ));
        jScrollPane1.setViewportView(tblPruebas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmAdmPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmAdmPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmAdmPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmAdmPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmAdmPruebas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPruebas;
    // End of variables declaration//GEN-END:variables
}
