/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Dtos.AnalisisDTO;
import Dtos.ClienteTablaDTO;
import Dtos.GuardarAnalisisDTO;
import Dtos.GuardarRegistroDTO;
import Dtos.PruebaTablaDTO;
import Negocio.IAnalisisNegocio;
import Negocio.IClienteNegocio;
import Negocio.IPruebaNegocio;
import Negocio.IRegistroNegocio;
import Negocio.NegocioException;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ang3lfco
 */
public class frmRegistrarAnalisis extends javax.swing.JFrame {
    private IClienteNegocio clienteNegocio;
    private IPruebaNegocio pruebaNegocio;
    private IRegistroNegocio registroNegocio;
    
    private List<ClienteTablaDTO> clientes;
    private List<PruebaTablaDTO> pruebas;
    
    private IAnalisisNegocio analisisNegocio;
    /**
     * Creates new form frmRegistrarCliente
     */
    public frmRegistrarAnalisis(IClienteNegocio clienteNegocio, IPruebaNegocio pruebaNegocio, IAnalisisNegocio analisisNegocio, IRegistroNegocio registroNegocio) throws NegocioException {
        initComponents();
        this.clienteNegocio = clienteNegocio;
        this.pruebaNegocio = pruebaNegocio;
        this.analisisNegocio = analisisNegocio;
        this.registroNegocio = registroNegocio;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        cargarClientes();
        cargarPruebas();
    }
    
    private void cargarClientes() throws NegocioException{
        cmbClientes.removeAllItems();
        cmbClientes.addItem("Selecciona un cliente");
        clientes = clienteNegocio.buscarClientes();
        for(ClienteTablaDTO c : clientes){
            String nombreCliente = c.getNombres() + " " + c.getApellidoPaterno() + " " + c.getApellidoMaterno();
            cmbClientes.addItem(nombreCliente);
        }
    }
    
    private void cargarPruebas() throws NegocioException{
        cmbPruebas.removeAllItems();
        cmbPruebas.addItem("Selecciona una prueba");
        pruebas = pruebaNegocio.buscarPruebas();
        for(PruebaTablaDTO p : pruebas){
            cmbPruebas.addItem(p.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox<>();
        cmbPruebas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRegistrar.setBackground(new java.awt.Color(52, 71, 169));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 19, 71));
        jLabel1.setText("Registro de Analisis.");

        cmbClientes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPruebas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cmbPruebas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbPruebasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(cmbClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPruebas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnRegistrar)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        String nombreClienteSeleccionado = (String) cmbClientes.getSelectedItem();
        String nombrePruebaSeleccionada = (String) cmbPruebas.getSelectedItem();
        
        if(!nombreClienteSeleccionado.equals("Selecciona un cliente") || !nombrePruebaSeleccionada.equals("Selecciona una prueba")){
            ClienteTablaDTO clienteSeleccionado = null;
            PruebaTablaDTO pruebaSeleccionada = null;
            
            for(ClienteTablaDTO c : clientes){
                String nombreCompleto = c.getNombres() + " " + c.getApellidoPaterno() + " " + c.getApellidoMaterno();
                if(nombreClienteSeleccionado.equals(nombreCompleto)){
                    clienteSeleccionado = c;
                    break;
                }
            }
            for(PruebaTablaDTO p : pruebas){
                String nombreCompleto = p.getNombre();
                if(nombrePruebaSeleccionada.equals(nombreCompleto)){
                    pruebaSeleccionada = p;
                    break;
                }
            }
            
            if(clienteSeleccionado != null && pruebaSeleccionada != null){
                int idCliente = clienteSeleccionado.getId();
                int idPrueba = pruebaSeleccionada.getId();
                JOptionPane.showMessageDialog(null, "Cliente: " + idCliente + " | Prueba: " + idPrueba);
                
                try{
                    AnalisisDTO a = analisisNegocio.guardar(new GuardarAnalisisDTO(LocalDateTime.now(), idCliente));
                    registroNegocio.guardar(new GuardarRegistroDTO(a.getId(), idPrueba));
                    JOptionPane.showMessageDialog(null, "Analisis y Registro registrado.");
                    this.dispose();
                }
                catch(NegocioException e){
                    JOptionPane.showMessageDialog(null, "error. " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void cmbPruebasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbPruebasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPruebasMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmRegistrarAnalisis().setVisible(true);
//            }
//        });
//    }
    private javax.swing.JComboBox<ClienteTablaDTO> cmbClientes2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JComboBox<String> cmbPruebas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
